version: "3.8"

services:
  pgvector:
    image: pgvector/pgvector:pg18

    command:
      [
        "postgres",
        "-c", "max_connections=300",
        "-c", "shared_buffers=1GB",
        "-c", "work_mem=32MB",
        "-c", "maintenance_work_mem=512MB",
        "-c", "effective_cache_size=3GB",
        "-c", "wal_buffers=16MB",
        "-c", "checkpoint_completion_target=0.9",
        "-c", "wal_level=replica",
        "-c", "port=5432",
        "-c", "timezone=UTC",
        "-c", "log_min_duration_statement=500",
        "-c", "log_error_verbosity=default",
        "-c", "default_statistics_target=100",
        "-c", "shared_preload_libraries=pg_stat_statements",
        "-c", "pg_stat_statements.max=5000",
        "-c", "pg_stat_statements.track=all"
      ]

    environment:
      POSTGRES_PASSWORD: SENHA_POSTGRES

    ports:
      - "5432:5432"

    volumes:
      - postgres18_data:/var/lib/postgresql

    networks:
      - SUA_REDE_AQUI

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 4G

volumes:
  postgres18_data:
    driver: local

networks:
  SUA_REDE_AQUI:
    external: true
    name: SUA_REDE_AQUI